image: daewok/lisp-devel

stages:
  - build

before_script:
  - apt-get update -qy
  - apt-get install -y git-core
  - cp -r /builds/ediethelm/trivial-timer ~/quicklisp/local-projects/trivial-timer
  - git clone https://gitlab.com/ediethelm/trivial-utilities.git ~/quicklisp/local-projects/trivial-utilities


sbcl-build:
  stage: build
  script:
    - sbcl --non-interactive --eval "(ql:quickload :trivial-timer)"


ccl-build:
  stage: build
  script:
    - ccl --eval "(let ((*debugger-hook* (lambda (c m)
                                           (declare (ignore c m))
                                           (uiop:quit 1))))
                    (ql:quickload :trivial-timer))"

